### ISSUE TITLE
Display settings icon in the status bar

### ISSUE THREAD

**Issue by NoahAndrews** [heyman/heynote#100]
I had no idea there even was a Settings dialog until I saw the PR that overhauls it. A gear in the status bar would make it much easier to find. I think it would also be reasonable to display the app version on the settings dialog, since About is similarly hidden.

By the way, the menu option is "Preferences", while the dialog says "Settings". At least on non-Mac platforms, the better menu option name is probably "Settings".

**Comment by heyman** [comment]
Version is now also displayed in the Settings: #163
