### ISSUE TITLE
Font support

### ISSUE THREAD

**Issue by mgu1206** [heyman/heynote#103]
I couldn't find any option in preferences about font setting.
Since Korean (may be the same for other Asian languages) doesn't look good.
Is there any schedule for supporting font types?

**Comment by alvin96** [comment]
Agree, I often use heynote to keep my code snippet, I also need custom font support to use font ligatures

**Comment by princox** [comment]
👍

**Comment by dhruvkb** [comment]
I recently voiced support for this feature in this comment https://github.com/heyman/heynote/pull/33#issuecomment-1870852343.

**Comment by heyman** [comment]
I've given it more thought, and I've come around to the idea of making it possible to configure the font. 

I've implemented it in #147. It should be working, and I just need to write some tests before merging.
