### ISSUE TITLE
Microsoft Defender SmartScreen prevented an unrecognised app from starting

### ISSUE THREAD

**Issue by alejsm** [heyman/heynote#117]
I get this message from Windows when I try to install Heynote:

Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

**Comment by feh-pined0** [comment]
Hi @alejsm, im not a repo maintainer, but this behavior is expected as the App is not currently signed on Windows builds (thats why it shows as unrecognized by smartscreen). It is also documented on the [project's readme](https://github.com/heyman/heynote#heynote)

**Comment by heyman** [comment]
🙄☝️
