### ISSUE TITLE
Feature request:  tools for manipulating text

### ISSUE THREAD

**Issue by codingHippo** [heyman/heynote#119]
It would be great to have a mode for manipulating text.
With tools somewhat like:
https://marketplace.visualstudio.com/items?itemName=qcz.text-power-tools#:~:text=Text%20Power%20Tools%20is%20an,the%20original%20source%20remains%20unchanged.

and/or support for running regular expression of the content in one black.

**Comment by heyman** [comment]
I feel this is a lot of feature requests in one :). [Text Power Tools](https://marketplace.visualstudio.com/items?itemName=qcz.text-power-tools) seems to have 240+ commands for text manipulation and I'm not going to be implementing them all. In a potential future where Heynote supports extensions, someone could maybe implement such an extension for Heynote.
