### ISSUE TITLE
Feature Request: Add PopClip Extension

### ISSUE THREAD

**Issue by a26nine** [heyman/heynote#121]
[PopClip](https://www.popclip.app/) is a MacOS app for text actions that provides the ability to take instant actions on the selected text.

It has a [wide variety of extensions](https://www.popclip.app/extensions/). It would be really helpful to have one for HeyNote, where the selected text can directly be pushed into a block in HeyNote.

![294126489-dd48e0e9-561a-4ae1-a6bd-93a15485cdfe](https://github.com/heyman/heynote/assets/103454930/f9bafba8-6892-4b55-918f-69b1915cdb34)

**Comment by heyman** [comment]
Do you know if there are some simple measures we could take to make PopClip work with Heynote? They claim that it should work when "you select text in any app", and I wonder what is currently preventing it from working.

**Comment by heyman** [comment]
I haven't used PopClip, but from glancing at their docs, I'm guessing that it should already be possible to create such an extension using AppleScript.

**Comment by a26nine** [comment]
I created it some time ago: https://github.com/a26nine/popclip-heynote. Please feel free to make changes!
