### ISSUE TITLE
Feature Request: Select TXT File Path

### ISSUE THREAD

**Issue by a26nine** [heyman/heynote#124]
All the HeyNote data is currently stored locally in `~/Library/Application Support/Heynote/buffer.txt`. It would be beneficial to have an option to configure the file path as required.

**Comment by NoahAndrews** [comment]
That's already implemented as an option in the config file. See #27.

**Comment by heyman** [comment]
And with #130, the Settings dialog now have a UI for it

**Comment by a26nine** [comment]
Thanks, guys!
