### ISSUE TITLE
Feature request: config file

### ISSUE THREAD

**Issue by nbbaier** [heyman/heynote#131]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Currently, it is possible to sync buffers across machines by committing buffer.txt to a gh repo, keeping it in a cloud folder, etc. But it is not possible to sync config. This isn't urgent, because the settings are rather simple, but if more features are added, making sure settings are unified could be an issue.

**Describe the solution you'd like**
Allow users to config heynote via a config file that could be synced across machines. This would also allow for easy restore of heynote settings when setting up a new machine

**Comment by Petemir** [comment]
I'm on Ubuntu Linux. I see a `~/.config/Heynote/config.json` file (the schema is [here](https://github.com/heyman/heynote/blob/bb7c4168da1d76773f83f8f9481f01ee186b410c/electron/config.js#L27)), which does have the app's settings (among other things like currency info):
```
{
  "settings": {
    "showLineNumberGutter": true,
    "showFoldGutter": true,
    "keymap": "default",
    "emacsMetaKey": "meta",
    "allowBetaVersions": false,
    "enableGlobalHotkey": false,
    "globalHotkey": "CmdOrCtrl+Shift+H",
    "bufferPath": ""
  },
  "theme": "dark",
  "currency": {
    ...
  }
}
```

Maybe you could try syncing this file to see if it works?

**Comment by nbbaier** [comment]
Ah yes good catch! It's `~/Library/Application Support/Heynote/config.json`.
