### ISSUE TITLE
Bug: Tray icon missing

### ISSUE THREAD

**Issue by KyleFN** [heyman/heynote#132]
**Describe the bug**
The system tray doesn't have a visible icon.

**To Reproduce**
1. Enable "Show system tray"

**Expected behavior**
Should have a visible icon.

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.10
 - Version: 1.6.0-beta

**Additional context**
Using a dark theme on KDE if that matters.

**Comment by heyman** [comment]
Thanks for the report! This is a bit tricky for me to debug as I don't have regular access to a Linux desktop computer. So if anyone running Heynote on Linux would like to help out, that'd be greatly appreciated.

I wonder if it's just a matter of `.ico` files not working as Tray icons on Linux:
https://github.com/heyman/heynote/blob/37265d779620ba2ba82b287dd54ac0dbcdce90a4/electron/main/index.ts#L152-L156

The [Electron docs](https://www.electronjs.org/docs/latest/api/tray) are not very clear.
