### ISSUE TITLE
The new tray icon feature does not seem useful on Windows

### ISSUE THREAD

**Issue by NoahAndrews** [heyman/heynote#137]
**Describe the bug**
Closing the heynote window makes the application exit entirely, including the tray window. This means that heynote must always be shown in the taskbar in order for its global hotkey to work, and I can't think of any scenarios where it makes sense to click on the tray icon instead of the taskbar entry.

**To Reproduce**
1. Enable the tray icon
2. Close the heynote window
3. Watch the tray icon disappear

**Expected behavior**
heynote should keep running in the background, with the tray icon displayed, and the global hotkey should continue to work.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.0-beta

**Comment by heyman** [comment]
You're right. Should be fixed in #139

**Comment by SimonB97** [comment]
Hi, how do i enable the try icon on windows?

**Comment by heyman** [comment]
In the Settings dialog (`File -> Settings` IIRC)

**Comment by SimonB97** [comment]
> > Hi, how do i enable the try icon on windows?
> 
> In the Settings dialog (`File -> Settings` IIRC)

what settings dialog? 
I can't find any settings in this app, just the shortcuts in the first cell..

**Comment by heyman** [comment]
Ah, you probably have to press `Alt` to show the program menu. 

In the latest beta version (released a couple of minutes ago) there's also a button in the status bar that opens the settings dialog.

**Comment by SimonB97** [comment]
> Ah, you probably have to press `Alt` to show the program menu.
> 
> In the latest beta version (released a couple of minutes ago) there's also a button in the status bar that opens the settings dialog.

that works, thanks a lot for the quick help!
