### ISSUE TITLE
Feature request: Sequence diagrams

### ISSUE THREAD

**Issue by OmidH** [heyman/heynote#144]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
My feature request is related to a problem I often encounter. I frequently need to think through and visualize software and process flows, especially when planning or troubleshooting or having ideas and just need to think it through. Heynote is an amazing piece of software to write down ideas, but it lacks a tool/block for creating sequence diagrams.

**Describe the solution you'd like**
To address this, I propose integrating a feature similar to what is offered by [js-sequence-diagrams](https://bramp.github.io/js-sequence-diagrams/). This tool provides an intuitive way to draw sequence diagrams, which are important for understanding, discussing and communicating data and process flows. The ability to easily create and embed these diagrams within Heynote would significantly enhance its functionality for users like me who deal with software design and process management and also in my opinion it would not break the spirit behind heynote as an easy to use block based editor.

**Comment by heyman** [comment]
Sorry, I think that is out of scope for Heynote. I can see that it could be useful to users who often make those kinds of diagrams, but I can also think of 10 other features that would be useful to a sub-group, but implementing all of them would be detrimental to Heynote as a whole.
