### ISSUE TITLE
Add quokka js to allow for js/ts inline evaluation.

### ISSUE THREAD

**Issue by Jargonius** [heyman/heynote#149]
It would be nice to have functionality similar to the math block for code blocks.  I'm not sure what's out there for other languages but for js/ts quokka exists.  I know you want to keep things simple so I'm not sure what you think of this but I think it would be useful to tinker around in the code and see simple results.
https://quokkajs.com/

**Comment by heyman** [comment]
While quokkajs seems cool, I think this is out of scope for Heynote at the moment.

**Comment by Jargonius** [comment]
I understand.
