### ISSUE TITLE
Feature request: Support Date Times

### ISSUE THREAD

**Issue by tomer-ben-david** [heyman/heynote#158]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to convert dates to unixtimestamp and convert from one time zone to another this happens a lot during coding, testing, troubleshooting.

**Describe the solution you'd like**
Examples:
startDate = 2024-01-11 05:38:21 NY to UTC
endDate = 2024-01-11 05:38:21 UTC
endDateUnixTimestamp = endDate to Unixtimestamp
totalTime = endDate - startDate
totalTimeMinutes = totalTime in minutes
7 hours in minutes
2 days 7 hours 2 seconds in seconds

**Describe alternatives you've considered**
notepadcalculator.com
Soulver 3
Numpad.io 

**Additional context**

**Comment by heyman** [comment]
Math blocks in Heynote are powered by Math.js. Until dates/times are supported in Math.js, Heynote is very unlikely to support it. There is a discussion about adding support for date/time datatypes in Math.js: https://github.com/josdejong/mathjs/discussions/2695
