### ISSUE TITLE
Bug: |Ctrl + Shift + Enter   Split the current block at cursor position| does not work

### ISSUE THREAD

**Issue by gerroon** [heyman/heynote#164]
**Describe the bug**
`Ctrl + Shift + Enter   Split the current block at cursor position ` justs adds a new block way at the bottom of the page, it has nothing to do with splitting to a new block

**To Reproduce**
Put the cursor in the middle of a block
Ctrl + Shift + Enter ->   Split the current block at cursor position

**Expected behavior**
It should split the current block?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.

**Comment by diorama-sky** [comment]
in Mac block not split when:
⌘ + Shift + Enter
OS: Mac 13.3.1 (a) 

However, the block is split when:
 ⌥ + ⌘ + Enter

**Comment by heyman** [comment]
The keybinding for splitting the current block changed with #85

If you first started using Heynote before that was merged you might still have the old keybindings in the welcome message at the top of the buffer (removing the buffer file would create a new one with the correct keybindings at the top). 

Here you can see the current keybindings:
https://github.com/heyman/heynote?tab=readme-ov-file#what-are-the-default-keyboard-shortcuts
