### ISSUE TITLE
Feature request: Add Bash syntax highlighting

### ISSUE THREAD

**Issue by superDuperCyberTechno** [heyman/heynote#168]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Bash isn't supported by your syntax hightlighting.

**Describe the solution you'd like**
Add Bash syntax highlighting.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peterjaric** [comment]
There is a Shell mode among the supported languages and when I entered a simple bash script it even auto-detected it:

```
#!/bin/bash

cd dir
ls
```
