### ISSUE TITLE
Feature request: programmer maths 

### ISSUE THREAD

**Issue by RobChaferDID** [heyman/heynote#169]
Your maths sections can do 'normal' maths. I can type in 0xe0000 and it will show the decimal (although it shows 57.344 when my locale would suggest 57,344). However, I can't type in 57344 and see the hex or binary for it. It would also be nice to do bit operations: 0xe0000^56 for example (for xor).

**Comment by peterjaric** [comment]
Math.js (that powers the Math blocks) supports functions, and among them there is a [hex()](https://mathjs.org/docs/reference/functions/hex.html) function that seems to convert to hex representation of a number. There is also a bin() function.

As for bitwise operations, there is [bitAnd](https://mathjs.org/docs/reference/functions/bitAnd.html) and [bitXor](https://mathjs.org/docs/reference/functions/bitXor.html) for example.

**Comment by heyman** [comment]
Heynote, like most programming languages, use `.` as decimal character no matter you locale. The `,` character is used as separator in arrays and matrices.

**Comment by NoahAndrews** [comment]
You can use the new ability to change the formatting function to make a Math block that gives all results in hex (or another number system). Just start the block off with this:

```
_format = format
format(x) = _format(x, {notation:"hex"})
```

Screenshot: 
![image](https://github.com/heyman/heynote/assets/10224994/e0d75457-1cf9-44cd-bf06-5f0fedc440fd)
