### ISSUE TITLE
Feature request: Math block: timezone conversion and date/time -> timestamps

### ISSUE THREAD

**Issue by ubuntudroid** [heyman/heynote#175]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
When coding I often work with date and time strings. This usually involves timezone conversions and or conversions from/to epoch timestamps. Right now Heynote Math blocks cannot help with that.

**Describe the solution you'd like**
Similar to the basic unit conversions, timezone conversions like "12 AM 4/23/24 CET in GMT-7" or epoch timestamp conversions like "12 AM 4/23/24 CET in epoch ms" (and vice versa) would be super helpful.

**Describe alternatives you've considered**
Right now I use third party tools like epochconverter.com, but this takes longer than necessary and I cannot make quick follow-up calculations like in a heynote math block.

**Comment by heyman** [comment]
Hi! See: https://github.com/heyman/heynote/issues/158#issuecomment-1888847342

**Comment by ubuntudroid** [comment]
Oh, I did an issue search first, but somehow totally missed that request. Sorry about that!

**Comment by heyman** [comment]
No worries! I did a search for `datetime` first as well with zero Github issue results, but I *knew* there was an issue about it, so searching for `date time` did the trick :).
