### ISSUE TITLE
Feature request: Open editor over fullscreen applications

### ISSUE THREAD

**Issue by anthonybench** [heyman/heynote#178]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**TLDR*
When I open heynote (macos) in a virtual desktop hosting a fullscreen application window, it jumps back to an open desktop. There are other note apps that pop up the editor above anything/everything else, and that behavior allows for swift use, would be awesome here

**Additional context**
Macos Sanoma

**Comment by heyman** [comment]
Yeah, having it popup on top sounds better. I'm not sure how that can be achieved though. I never use the fullscreen mode on Mac because of the extremely irritating "screen sliding" behaviour that seems to occur a lot.

**Comment by anthonybench** [comment]
@heyman do you mean when you have 1 or more fullscreen-app windows, and it jerks back to one with an open desktop when you run certain applications? Happens to me when i open zoom meetings, hate that.

Relevant to hear, looking through the feature request, I did see something effectively identical to this request, and the maintainer's response was to use a window manager, as this is only an issue on macos.

Even if it **is** only an issue on macos, it would still be amazing to implement out-of-the-box support for "float over everything" behavior. I implore anyone to fetch "Scrap Paper" from the app store and try it out and see what i mean, I'd go so far as to say that a key advantage/reason for having a note app is the ability to pull it up and hide it where ever you are, since the scenario of wanting to write something while you're reading from a fullscreen application is highly plausible.

I love this app, I saw it mentioned in *Console* news letter and loved it immediately, if they added this for mac users, I'd be thrilled.

**Comment by heyman** [comment]
I found [this](https://github.com/electron/electron/pull/14122) and managed to get Heynote to stay floating on top of a fullscreen window using the following code:

```javascript
win.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true})
```

*However*, when entering fullscreen, the Heynote window will automatically appear on top. And the only way to hide it is to either minimize or close the window (removing focus from the Heynote window by clicking on the fullscreen app would not hide Heynote). 

I believe the `visibleOnFullScreen` feature was implemented for the use case of having a program that would *always* float on top of all other programs, which doesn't really match our use-case.

**Comment by heyman** [comment]
One option could be to add an "Always on top" option, which - when enabled - would make Heynote always stay floating on top of other windows. It would solve #38, but it would do more than just allow Heynote to appear on top of fullscreen workspaces.

**Comment by heyman** [comment]
I've implemented an "Always on top" setting in #179. Seems to work on Mac, but needs to be tested on Windows and Linux as well.

**Comment by anthonybench** [comment]
@heyman That's awesome, I see your ci/cd steps pass on it, will that make into an upcoming release?

**Comment by heyman** [comment]
It needs to be tested on Windows and Linux to see that it works and doesn't mess up showing/hiding Heynote using the global hotkey. Once that's done, I'll merge it, and it'll make it into a new version.

**Comment by anthonybench** [comment]
@heyman
For me:
Hitting the global hotkey (made sure no other application is also mapped to that hotkey) brings focus to heynote.
└▶ Hitting it again will bring focus back to the application that last had it.

Would be awesome if it hid/minimized heynote.

Love it though, already use it a ton!

**Comment by heyman** [comment]
Ah, that's the intended behaviour. With the "Always on top" setting turned on, it should hide though.

**Comment by anthonybench** [comment]
@heyman Hey I'm currently on `1.7.0` of heynote on `MacOS Sonoma 14.3.1`, and it still does not have the "on top / hide" behavior for full screen apps. Perhaps I read the release notes wrong for `1.7.0`, and it's not suppose to be there yet?

**Comment by anthonybench** [comment]
For what it's worth, I power-cycled my mac too.
