### ISSUE TITLE
Feature request: Highlight first line of block

### ISSUE THREAD

**Issue by neeraj-ec** [heyman/heynote#180]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
It would be really helpful if 1st line of the block is highlight with larger text. This way it would be easy to locate a block among many.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heyman** [comment]
I want the blocks to be a *lightweight* separator while still keeping the feeling of being in one large text buffer. I believe this change would go against that and therefore not planning to change this, sorry.
