### ISSUE TITLE
Feature request: Show Help Information

### ISSUE THREAD

**Issue by thomasbiddle** [heyman/heynote#184]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
I am not deleting the original help information so that I can reference it easily. I'd like to get it out of the way, but have an easy way to pull it back up.

**Describe the solution you'd like**
- Keep the original pre-filled help info on first load as-is; nothing changed there
- Add a module / tool-tip with the same information; this can be pulled up by clicking on 'Help' and selecting 'Shortcuts/Info' or by hitting ⌘H

**Describe alternatives you've considered**
Don't think necessary; I like my solution

**Additional context**
I'm speaking of this info:

![image](https://github.com/heyman/heynote/assets/1205663/9879272a-fe3d-4dec-b369-505102dc14a3)

**Comment by Thomas101** [comment]
Mine is the same, I can't delete the first block for fear of never remembering how to create a new one! Maybe a button in the bottom bar or a right-click context menu would be helpful

**Comment by simonratner** [comment]
Additionally, the original block is static so doesn't update when shortcuts are added during version upgrade. Being able to pull up this list from the help menu would always have up to date shortcuts.

Similar would be useful for Math.js "sample block", as a quick reference for unit conversions for example.

**Comment by kjk** [comment]
FYI: I've implemented such functionality in my fork via several ways to get at help.

One is context menu:

![image](https://github.com/heyman/heynote/assets/7935/dd9fd5e8-2ce4-4092-bb40-4f1139fb33c2)

There's also a `Help` button in status bar:

![image](https://github.com/heyman/heynote/assets/7935/9feb9347-6bf7-41f9-9410-0952b322f4b7)

My fork: https://github.com/kjk/edna/issues, https://edna.arslexis.io/

**Comment by heyman** [comment]
This has been fixed by #242 which adds a dedicated [documentation page](https://heynote.com/docs/). A link to this page has been added to Heynote's Help menu and it'll be included in the next release.
