### ISSUE TITLE
Feature request: Remember window state on close

### ISSUE THREAD

**Issue by superDuperCyberTechno** [heyman/heynote#185]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Every time I launch the application, I need to move it out of the way as it spawns in the middle of the screen.

**Describe the solution you'd like**
Remember where the window was last placed and spawn there on next launch. Remembering size is also pretty important but it already seems to do that.

**Comment by heyman** [comment]
Already fixed by #173. 

Will be part of the next version (first in a pre-release, so turn on beta versions if you want to get it as quick as possible).
