### ISSUE TITLE
Feature Request: Add GoLang, Ruby, Rails and Vue.js

### ISSUE THREAD

**Issue by ryanlitalien** [heyman/heynote#19]
Hello!
I'm working on two projects at the moment, one in Go, and the other a Ruby/Rails/Vue project. I'd like to switch the blocks to those languages. Is there a formal way to request these three (four if you count Rails)?

Great work so far!

(found via HN)

![image](https://github.com/heyman/heynote/assets/1479756/1662e9a7-b507-4c8a-bd64-bc866525b093)

**Comment by endigma** [comment]
Added to #10

**Comment by heyman** [comment]
Closing in favor of #10
