### ISSUE TITLE
Bug: Command-Shift-Enter Does not Split the current section

### ISSUE THREAD

**Issue by whoiskevin** [heyman/heynote#207]
Using the shortcut to split the current section at the cursor just scrolls to the bottom in a new section.  Unless I am mistaken the Cmd-Shift-Enter shortcut should split the current section at the cursor creating a new section with the content below the current cursor position.

**To Reproduce**
1. Add a section and type 'line 1' press enter twice and type 'line 2'
2. Arrow up to the blank line between line 1 and line 2
3. Press the short cut Cmd-Shift-Enter
4. new section is added at bottom of the buffer

**Expected behavior**
Would expect line 1 to remain in a separate section and a new section would be created with line 2

**Screenshots**
<img width="1363" alt="screenshot 2024-02-21 at 9 26 52 AM" src="https://github.com/heyman/heynote/assets/280315/bcf5f495-2a7b-4f56-a0d3-d1b4662a392c">

**Desktop (please complete the following information):**
 - OS: MacOS 14.3.1
 - Version 1.7.0

**Comment by heyman** [comment]
The key binding was changed to `Cmd-Option-Enter`. 

Here are the current key bindings:
https://github.com/heyman/heynote?tab=readme-ov-file#what-are-the-default-keyboard-shortcuts

**Comment by whoiskevin** [comment]
Thanks.  Wasn't aware of the changes.
