### ISSUE TITLE
Feature request: Add shortcut CMD/Control + SHIFT + Z for redo along side Control + Y on Windows.

### ISSUE THREAD

**Issue by c3cris** [heyman/heynote#212]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Redo with universal shortcut of CMD/Control + SHIFT + Z

**Describe the solution you'd like**
Add control + shift  + z for Redo text on Windows 
Most likely Command-Shift-Z for Mac?

**Describe alternatives you've considered**
None

**Additional context**
Control+Y is a windows only shortcut forced by Word/Excel and other Windows 1st party apps.  I would love support for CMD/Control + SHIFT + Z.
Keep in mind that this github textarea I am using has support for both Control + Y and Control + Shift +Z .
QED.

**Comment by kjk** [comment]
FYI: I did that in my fork (see https://github.com/kjk/edna/commit/d2e9c4f5ca2db4e8dfe7d2a2695ec8333cde58c6 for the change).

Basically in `keymap.js` you need to add:
```
  // for some reason CodeMirror uses Ctrl + Y on Windows
  // and only binds Mod-Shift-z on Mac and Linux
  // Windows editors also use Ctrl-Shift-z
  if (platform.isWindows) {
    spec.push(["Mod-Shift-z", redo]);
  }
```

**Comment by c3cris** [comment]
Merged
