### ISSUE TITLE
Bug: Command-H does not hide the application

### ISSUE THREAD

**Issue by aleshh** [heyman/heynote#214]
**Describe the bug**
On macOS, the Command-H keyboard shortcut does not work correctly. It should hide the application, instead it makes it inactive but keeps it on the screen. This also prevents other applications from hiding Heynote, e.g. "Hide Other Qindows."

**To Reproduce**
1. Activate Heynote
2. Type Command-H or select "Hide Heynote" from the Heynote menu

**Expected behavior**
Heynote hides

**Desktop (please complete the following information):**
 - OS: MacOS 14.3.1
 - Version 1.7.0
 -

**Comment by heyman** [comment]
Strange! I'm not able to reproduce this on MacOS 13.5.1.

**Comment by aleshh** [comment]
Ugh, my bad—I just updated the application and the problem went away

**Comment by heyman** [comment]
👍

If you didn't try restarting Heynote when you were experiencing the bug (but maybe you did?), it could be that it was the restart that fixed it, and that the bug still exists in some edge case.

**Comment by kristojorg** [comment]
I'm still seeing this on 1.7.0 when I don't show the app in the dock, or after enabling the setting to show it in the dock it then won't hide until restarted

**Comment by dljsjr** [comment]
I'm seeing the same thing as @kristojorg on the 1.8 beta channel.

If `Show In Dock` is enabled, then `Cmd+H` works.

If `Show In Dock` is disabled, then `Cmd+H` does *not* work.

**Comment by aleshh** [comment]
I think this is how MacOS is intended to work. Cmd-H does not work on menu-bar applications. I wish it weren't so, but for this reason I run Heynote as a dock app: lets me hide it with the keyboard shortcut and other system utilities.

**Comment by dljsjr** [comment]
I should probably have opened a separate issue cuz this is really an "X/Y problem" situation.

What I'm really looking for is a way to launch HeyNote at login without the main window popping up. I run it as a menu bar only app to keep my Cmd Tab situation clean. But that also means the "hide at login" option doesn't work cuz it doesn't receive the Hide event.
