### ISSUE TITLE
请问一次只能开一个窗口？不能保存为文件，同时打个多个文件吗

### ISSUE THREAD

**Issue by limaofu** [heyman/heynote#215]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
请问一次只能开一个窗口？不能保存为文件，同时打个多个文件吗

**Comment by heyman** [comment]
> Can I only open one window at a time?

Yes.

> Can't I save it as a file?

The whole buffer is saved as a file on disk. See: https://github.com/heyman/heynote?tab=readme-ov-file#where-is-the-buffer-data-stored

> Can I create multiple files at the same time?

No.
