### ISSUE TITLE
Feature request: how to put checkbox in the table at markdown format?

### ISSUE THREAD

**Issue by YeoungwooKim** [heyman/heynote#222]
**Have you searched existing Github issues to see if someone has already requested this feature?**
No

**Is your feature request related to a problem? Please describe.**
I would like to add checkboxes to some of the fields inside the table in Markdown format, but it doesn't seem to be rendering properly. Is this a feature that is not supported?

**Describe the solution you'd like**

| something  | something2 |
| ------- | --------------- | 
| a | [x] task     |
| b | [ ]  task1<br/>[ ] task2           | 

And I almost forgot to tell another feature.
Is there any ways to customize keymaping?
such as "One line delete -> cmd + d".

**Comment by YeoungwooKim** [comment]
and I forgot to tell another feature.
Is there any ways to customize keymaping?
such as "One line delete -> cmd + d".

**Comment by heyman** [comment]
Checkboxes in Markdown tables are not supported. Does the Markdown syntax even support it? I noticed that Github doesn't render checkboxes either.

Custom keymapping is on the to-do list.
