### ISSUE TITLE
Bug: Cant use currency value as variable for next operation

### ISSUE THREAD

**Issue by myounus96** [heyman/heynote#224]
**Describe the bug**
Cant use currency value as variable for next operation.

**Screenshots**
<img width="300" alt="image" src="https://github.com/heyman/heynote/assets/13608139/8f46a45a-7f46-41d7-9b97-064328ae0d85">

**Comment by rmjohnson** [comment]
FWIW you can do this if you specify `1 USD`. This feels like a mixing of units thing to me (e.g. "how do I add 1 to $1 (USD)? Is this 1 EUR or 1 USD?" I have to specify the 1 I'm adding is $1 (USD)).
![image](https://github.com/heyman/heynote/assets/249152/cda61fa8-252f-43a2-896f-5026cf60973e)

**Comment by myounus96** [comment]
Thanks
