### ISSUE TITLE
Question: How can I convert the buffer.text from plain text to JSON

### ISSUE THREAD

**Issue by JJack27** [heyman/heynote#257]
Hi @heyman, I'm planning to refactor the content of buffer.txt from plain text to json. I'm wondering where should I start?

**Comment by heyman** [comment]
You need to look into how [Lezer](https://lezer.codemirror.net/) and [CodeMirror](https://codemirror.net/) - which powers Heynote - works. Please note that I'm not interested in implementing this change into Heynote.
