### ISSUE TITLE
Feature request: Clickable hyperlinks

### ISSUE THREAD

**Issue by Victor239** [heyman/heynote#26]
Hyperlinks for at least the Plain text and Markdown languages would be nice if they were clickable.

**Comment by heyman** [comment]
They should be clickable when holding down `Ctrl`/`Cmd`

**Comment by Victor239** [comment]
Ah you're right, I didn't expect that as the mouse cursor doesn't change into the hand one like it does for hyperlinks in a web browser. Thanks, this works sufficiently for me.
