### ISSUE TITLE
Bug: Line Break Function Not Working in v1.8.0

### ISSUE THREAD

**Issue by phoben** [heyman/heynote#271]
Description:
I'm encountering an issue with line breaks in Heynote v1.8.0. The problem started occurring recently (within the past few days), although it was working properly before.

Issue Details:

Unable to create new lines using either Enter key or Ctrl+Enter
Cannot paste multi-line text into Heynote
This functionality was working correctly in the same version before
Steps to Reproduce:

Open Heynote v1.8.0
Try to create a new line using Enter key
Try to create a new line using Ctrl+Enter
Try to paste multi-line text from clipboard
Expected Behavior:

New lines should be created when pressing Enter or Ctrl+Enter
Multi-line text should paste correctly with line breaks preserved
Actual Behavior:

No line breaks are created when pressing Enter or Ctrl+Enter
Multi-line text pastes as a single line
Environment:

Heynote Version: 1.8.0
Please let me know if you need any additional information to investigate this issue.

**Comment by heyman** [comment]
Could you check if you get any error in the Developer Console (press `Alt` to revela the menus, and then `View -> Toggle Developer Tools`)?

The only thing I could think of is that it's something in the text buffer that causes the error. You could check and see if clearing the buffer fixes the problem. You could do that by deleting the current buffer file (don't forget to make a backup of the current one) and then starting Heynote. The path of the buffer files depends on the OS, and you can find the different paths here: https://heynote.com/docs/#user-content-the-buffer-file

If clearing the the buffer file fixes it, it would be useful to get a minimal version of the buffer file that causes the error.
