### ISSUE TITLE
Bug: Crashes instantly on startup after upgrade to macos Seqoia

### ISSUE THREAD

**Issue by kahoot-karl** [heyman/heynote#273]
**Describe the bug**
Crashes on startup

**To Reproduce**
1. Open heynote
2. Crashes

**Expected behavior**
Should not crash

**Screenshots**

https://github.com/user-attachments/assets/56c2ff8a-337f-473f-aa1f-110be28fcbac

**Desktop (please complete the following information):**

![image](https://github.com/user-attachments/assets/3f8e5b5b-bf6f-4a1a-aa1f-0901e7b7a459)

**Comment by heyman** [comment]
I suspect you are not on the latest version. See #270.

**Comment by maltegrosse** [comment]
can confirm, latest version (1.8) fixes that issue

**Comment by heyman** [comment]
I haven't seen that error, and I don't know what might be causing it. 

The default path for your notes (on Mac) is:

`~/Library/Application Support/Heynote/buffer.txt` (`~` is your home directory)

so you shouldn't risk loosing them removing/reinstalling the app.
