### ISSUE TITLE
File syncing buffer.txt

### ISSUE THREAD

**Issue by heyman** [heyman/heynote#31]
Heynote should detect changes to buffer.txt, and load new contents from the file into the text buffer. The implementation does not need to be very advanced e.g. support merging etc. but it should be good enough that you can sit and work at one computer with buffer.txt in Dropbox, and then switch over to Heynote running on another computer and continue the work there.

**Comment by SasePriv** [comment]
I have a doubt, in the code when you open the app, it automatically reads the file where it is, so what you want to implement is if the file is overwritten while the app is open or do you mean connecting the app to a cloud ?

**Comment by heyman** [comment]
If the file is changed while the app is running, it should reload the content from the file.

**Comment by CatsMiaow** [comment]
I think there's also a way to sync to GitHub Gist.
Perhaps something like [GistPad](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs)

**Comment by heyman** [comment]
I'm not planning to implement any custom syncing other than file syncing.
