### ISSUE TITLE
Use Fend for better unit conversion & maths

### ISSUE THREAD

**Issue by zadeviggers** [heyman/heynote#36]
[Fend](https://github.com/printfn/fend/) supports a lot more units and more complex syntax than Math.js. It has built in support for variables, currency conversion, etc, so documents should be fully compatible.

You can use it through their wasm build, or directly through rust for a nicer api (if you switch to Tauri in the future).

**Comment by heyman** [comment]
It doesn't look like Fend would be close to a drop-in replacement for Math.js, and if it isn't, it's very unlikely that I would put the time into changing this.
