### ISSUE TITLE
FR: Always-on-top mode

### ISSUE THREAD

**Issue by luckman212** [heyman/heynote#38]
I will see if I can figure out how to make a PR for this, but...

It would be very nice to have a floating always-on-top window mode, so reference notes could be floated above VSCode (or any other window)

I had written a similar scratchpad type of tool for Hammerspoon and by setting a couple of flags on the Window type, you could get the window to float and also have a thinner titlebar (`NSWindowStyleMaskUtilityWindow`) which was quite appealing.

![image](https://github.com/heyman/heynote/assets/1992842/e20e13fc-5893-40ff-8fb2-2f5b7a4aaf05)

see https://developer.apple.com/documentation/appkit/nswindowstylemask/nswindowstylemaskutilitywindow

**Comment by Drugoy** [comment]
That's a task for your window manager.

**Comment by luckman212** [comment]
@Drugoy Unfortunately on macOS there is no such feature in the native WM, and no way for a 3rd party app to affect another app's windows to my knowledge.

**Comment by alilleybrinker** [comment]
There _are_ Mac window managers. You might look into Amethyst and see how they do it. https://github.com/ianyh/Amethyst

**Comment by luckman212** [comment]
I never said there were no window managers, just that there is no way for one to change the properties of another app's windows (for example setting the AlwaysOnTop attribute). 

Amethyst looks like a nice WM, but I see nothing in the docs about making windows float.
