### ISSUE TITLE
Feature Request: Selectable default block type

### ISSUE THREAD

**Issue by ChrisDowning** [heyman/heynote#39]
First: Fantastic app!

Right now, new blocks always start in "Plain text (auto)" mode when created with Cmd+Enter. It would be nice to be able to select this - I expect I will use Markdown >90% of the time, for example.

As an extension of this, other keyboard shortcuts (e.g. Cmd+{1..9}) could be mapped to the creation of new blocks in different modes.

**Comment by heyman** [comment]
I like it. Sounds like a useful enough feature and shouldn't be too complicated to implement.

Not sure about additional keyboard shortcuts though. Perhaps if/when we have a commands palette and custom keybindings, we can create commands for it that users could bind themselves.

**Comment by michaeldmueller** [comment]
Any progress on the default block type feature? Love the app and this improvement would make it even more useful

**Comment by heyman** [comment]
Fixed now! Will be in `1.8.0-beta.2`, which I'm planning to release today.
