### ISSUE TITLE
FR: Block map

### ISSUE THREAD

**Issue by acumenrev** [heyman/heynote#40]
When I have a lot of blocks, then I think it is good if we add a map that can help me to navigate instantly to the block I want instead of scrolling non-stop and searching for it. The idea is that we can have a name for each block that comes after a prefix (ex: #my-document), then there is a list that shows all of the block names. When I click on each name, the visible area in the editor will display the selected block

Btw, love your work Heynote

**Comment by heyman** [comment]
I've definitely thought about it, but currently, I don't want to add naming/tagging of blocks. The reason is that I want to keep the app simple and focused, and I think it goes against the "scratchpad nature" of Heynote a bit.
