### ISSUE TITLE
Backup the scratch pad, preferably on git

### ISSUE THREAD

**Issue by clmnin** [heyman/heynote#49]
Love the product. I've been using Markdown on VS Code to track my todos. This interface and the 'one page to rule them all' idea is much better.

But how can I backup my notes? I don't want to lose them as `heynote` can grow into my daily driver.

**Comment by Victor239** [comment]
If you're on Linux it's stored at `~/.config/Heynote/buffer.txt`.

**Comment by heyman** [comment]
I've just merged #27 which adds supports for using a symlink, and will also allow you to set a custom path for where buffer.txt is stored. So that will be in the next release.
