### ISSUE TITLE
Chrome on windows blocks downloading Heynote windows installer file.

### ISSUE THREAD

**Issue by amudhanp** [heyman/heynote#52]
I am trying to download Heynote windows installer using Chrome. Download is blocked with msg saying "Suspicious download blocked".
I have not tried with Web browsers but want to know why it is being blocked.

![image](https://github.com/heyman/heynote/assets/25737192/cbae8a39-08c9-418e-9a5f-e1a20bf2915c)

**Comment by heyman** [comment]
You can bypass it. 

The reason for the very scary looking warnings is because I don't want to pay a yearly subscription for an expensive certificate. Also, last I checked the process of setting up automatic signing of Windows executables looked quite messy.
