### ISSUE TITLE
Add option to hide macOS dock icon

### ISSUE THREAD

**Issue by nbbaier** [heyman/heynote#62]
First, let me say I'm really loving Heynote! Would it be possible add an option to allow users on macOS the option of hiding the app's dock icon? I'm accessing Heynote via a global hotkey, so I don't have much use for it and I prefer the option of hiding such apps.

**Comment by heyman** [comment]
Yes, I like it. Seems to be a one-liner to do that in electron as well: `app.dock.hide()`
