### ISSUE TITLE
Markdown links are not rendered

### ISSUE THREAD

**Issue by flaeppe** [heyman/heynote#67]
Doesn't seem to be clickable either. e.g.

```
[Google](https://google.com)
```

Could perhaps be rendered to something like below?

[Google](https://google.com)

**Comment by heyman** [comment]
All links should be clickable when holding down `Ctrl` (`Cmd` on Mac). 

It should be possible to make link syntax appear more like links (and make the actual text appear when the cursor is placed within them), but I'm not sure that I actually want the URL to be hidden.

**Comment by flaeppe** [comment]
I see, often times I use that syntax to hide lengthy URI:s.

An opposite thought could be to have a hot key to display a full URI.

Or some form of toggle hot key, perhaps that's only relevant for markdown though. Toggle rendering on/off

**Comment by heyman** [comment]
Ah, I see. My reasoning is that the Markdown mode isn't really a preview mode, so you want to be able to see the whole content.
