### ISSUE TITLE
Feature Request: Executable Blocks

### ISSUE THREAD

**Issue by theonewolf** [heyman/heynote#7]
It would be awesome to be able to execute a block and get its output as the next block or inline.

So not just note buffers, but tiny PowerShell / Shell / JS / Python snippets one could execute quickly.

Not the full weight of a Jupyter Notebook.  The key is the lightweightness of the block framework.

**Comment by endigma** [comment]
Maybe just executables via shebang?

**Comment by atma1c** [comment]
I would love to define a function in a Python block and be able to call it from the Math block (or even from Python block to begin with).
I have a need for several custom unit conversions and would like to define them as functions and run them later.

**Comment by dmd** [comment]
I **strongly** vote against this; it seems antithetical to the simple core functionality and opens up _so_ many cans of worms.

**Comment by hbd** [comment]
I agree with @dmd, however I think this concept would make for a perfect plugin. If heynote were to expose an API for sending the contents of a block to a plugin, then the plugin could return the output for heynote to display.

**Comment by heyman** [comment]
I have no plan to implement this feature. I can see that it could be useful, but it would make Heynote a very different program.

**Comment by OiYouYeahYou** [comment]
@heyman, while won't implement this, would you accept a PR to add this? Thanks :smile:
