### ISSUE TITLE
Zoom In hotkey (CTRL+ +) does not work

### ISSUE THREAD

**Issue by rellfy** [heyman/heynote#71]
CTRL + + does not work for me, but CTRL + - (Zoom Out) does.
I can only zoom in through the Edit menu (after clicking Alt).

**Comment by ImKaashif** [comment]
have you tried `CTRL` + `Shift` + `+`?
 That should work

**Comment by rellfy** [comment]
> have you tried `CTRL` + `Shift` + `+`? That should work

Thanks, that does work.
Interestingly, `CTRL`+`Shift`+`-` does not work. Not very consistent :grin:

**Comment by rellfy** [comment]
> have you tried `CTRL` + `Shift` + `+`? That should work

@ImKaashif  Thanks, that does work.
I noticed `CTRL`+`Shift`+`-` does not work for zooming out though. Not very consistent.

**Comment by ImKaashif** [comment]
@rellfy, I'm not sure but I guess they are using default keymap for zoom-in and zoom-out from codemirror, and it is similar to the linux terminal.

If we want, I think we can still override the default behaviour to zoom-in on `CTRL` + `=`, so that it seems consistent to `CTRL` + `-`

**Comment by heyman** [comment]
I think the default keymap for zoom in/out is coming from Electron. Is this on Windows? On Mac `CMD`-`+` works as expected.

**Comment by rellfy** [comment]
> I think the default keymap for zoom in/out is coming from Electron. Is this on Windows? On Mac `CMD`-`+` works as expected.

@heyman Linux/Fedora :)

**Comment by heyman** [comment]
Ok, I think `CTRL`+`+` makes more sense than `CTRL`+`Shift`+`+`, so that should be fixed

**Comment by heyman** [comment]
Someone has reported this as a bug in Electron:
https://github.com/electron/electron/issues/40674

And here someone proposes a workaround:
https://github.com/electron/electron/issues/5256#issuecomment-692068367

**Comment by TimTrademark** [comment]
Seems like the zoom in works with `ctrl` + `shift` + `+` as mentioned here: https://github.com/electron/electron/issues/15496#issuecomment-1725268407
