### ISSUE TITLE
Feature Request: I forgot the shortcuts and there's no documentation in the app :)

### ISSUE THREAD

**Issue by quicksnap** [heyman/heynote#74]
Would love for there to be a link in Help menu to somewhere that documents the shortcuts. Perhaps we can put a link to https://github.com/heyman/heynote/blob/main/electron/initial-content.ts for now until there's a better way.

**Comment by heyman** [comment]
Added to the [Readme](https://github.com/heyman/heynote?tab=readme-ov-file#what-are-the-default-keyboard-shortcuts) for now.
