### ISSUE TITLE
Feature Request: Hex and binary outputs for Math block

### ISSUE THREAD

**Issue by scottnm** [heyman/heynote#77]
It's awesome that the editor already supports doing math evaluation using hex values, binary values, values and even supports bitwise operations.

e.g.
> 0x10 | 0b11 `19`

Is there anyway to control what base/format the output is in? getting hex and/or binary output would be very useful! Definitely one of my most common and least served developer needs with my current tooling (mostly vim and powershell)

**Comment by heyman** [comment]
It's not possible to change the default base of the output. However, Math.js (which Heynote uses for the Math blocks), [has the functions](https://mathjs.org/docs/reference/functions.html#string-functions) `hex()`, `bin()` and `oct()` for base conversion:

<img width="260" alt="image" src="https://github.com/heyman/heynote/assets/54217/e8f524e8-913a-4c8b-b9c4-bde4ea5bed15">
