### ISSUE TITLE
FR: Enhance scratchpad concept

### ISSUE THREAD

**Issue by rsyring** [heyman/heynote#84]
I understand from #44 that Heynote is intended to be simple and that's part of its appeal.  However, I think you aren't far off from a tool that is significantly more useful.  Consider the following enhancements:

* Add a "document" concept that holds a set of blocks.  
  * New document created with ctrl+n
    * The name should default to something simple.  Let's just say "Scratchpad" for now.
  * New document created with ctrl+shift+n but this key combination opens an input dialog to let you set the name of the document.
  * Default content of first block is all the key combinations.  But it's text is selected when the note first loads after creation so that the first thing I type/paste replaces it.
  * Allow the document to be renamed.
* Add left navigation bar to show documents.  It can be expanded/collapsed with ctrl+b.
  * Show documents in descending order by creation date.
* Add global search capability, launched with ctrl+k, that matches doc names and block content.

Someone could never use documents and the user experience would be exactly the same.  But the above would enable being able to "start over" when a scratchpad gets too messy and/or group similar block content.  

Would also facilitate the concept of snippets which would be handy in a code-focused note taking app.  Add a few relevant CLI commands and this functionality could be easily integrated into a global launcher like Albert.  Now I'm a keystroke and just a bit of typing away from easily adding a new document, opening Heynote to that doc and "raising" the window, and/or sending its content to the OS clipboard.

Feel free to just close this as I realize its a stretch and don't want to waste your time.  But thought I'd at least get the idea out and maybe there's value in it some day.

**Comment by heyman** [comment]
I can see that such a program could be useful, but it would change Heynote into a different program than what I envision.
