### ISSUE TITLE
Allow configuring math.js formatting

### ISSUE THREAD

**Issue by NoahAndrews** [heyman/heynote#91]
math.js has [many options to configure the formatting of its output](https://mathjs.org/docs/reference/functions/format.html). Unfortunately, if you're using heynote and you're not happy with the default values, you have to add an explicit `format()` call everywhere that you want to override them, which is annoying and puts quotation marks around the result that you have to remove when pasting. It would be much better if we could configure the math.js formatting options in the heynote settings.

**Comment by heyman** [comment]
I've now fixed it (#92) so that string results won't render with quotation marks:

<img width="446" alt="image" src="https://github.com/heyman/heynote/assets/54217/4ce6f8fc-a74f-4808-958c-26d350551cb6">

What's the use case for changing the default? I'm hesitant to add settings/features that very few users would use.

**Comment by NoahAndrews** [comment]
Nice!

The default that got in my way was switching to exponent notation. As a software engineer, I sometimes calculate big numbers that I want be able to paste directly into my code.

**Comment by heyman** [comment]
I've managed to fix it so that one can override the default format function within a math block, like this:

```
_format = format
format(x) = _format(x, {notation:"exponential"})
...
```

It's working, but I'll have to tidy it up before I commit it.

<img width="497" alt="image" src="https://github.com/heyman/heynote/assets/54217/76f8accb-9147-4420-a915-cc5a582eb24a">

**Comment by NoahAndrews** [comment]
That was fast, thanks!

**Comment by NoahAndrews** [comment]
I think I prefer the behavior of copying exactly what's displayed
