### ISSUE TITLE
Difference with Typora

### ISSUE THREAD

**Issue by 4l1fe** [heyman/heynote#93]
Hey, interesting idea! But let me ask you what are the main differences with Typora? I've been using it succsefully for all the developer needs in writing.

**Comment by heyman** [comment]
I haven't used Typora, but from a quick look at the website it doesn't seem very similar to Heynote to me (apart from being an editor where you write stuff down).

**Comment by 4l1fe** [comment]
> it doesn't seem very similar to Heynote to me

Yes, it doesn't. Generally, it is a markdown WYSIWYG editor which is used for journaling work routins or a design process, for instance. 

I think how Heynote could be more productive or it is very specific? Unfourtunetelly, there is no well described use case, i hope you'll add it later.

As i see Heynote now(installed and tried), it is a blocks writing editor and seems to be closer to the idea of [LogSeq](https://logseq.com)
